name: ama_site
services:
  web:
    image: ama/web
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - "2501:80"
    develop:
      watch:
        - action: sync
          path: ./web
          target: /var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ORACLE_HOST=db
      - ORACLE_PORT=1530
      - ORACLE_SID=FREEPDB1
      - ORACLE_USER=AMA
      - ORACLE_PASSWORD=AMA
  db:
    image: gvenzl/oracle-free:23-slim
    ports:
      - "1530:1521"
    environment:
      - ORACLE_PASSWORD=AMA
    volumes:
    - oracle-data:/opt/oracle/oradata
    - ./database:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/AMA@//localhost:1521/FREEPDB1", "as", "sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
volumes:
  oracle-data: