SET SERVEROUTPUT ON;
ALTER SESSION SET CONTAINER = FREEPDB1;

DROP USER AMA CASCADE;

CREATE USER AMA IDENTIFIED BY AMA DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

ALTER USER AMA QUOTA 100M ON USERS;
GRANT CREATE SESSION TO AMA;
GRANT CONNECT, RESOURCE TO AMA;

GRANT CONNECT TO AMA;
GRANT CREATE TABLE TO AMA;
GRANT CREATE VIEW TO AMA;
GRANT CREATE SEQUENCE TO AMA;
GRANT CREATE TRIGGER TO AMA;
GRANT CREATE SYNONYM TO AMA;
GRANT CREATE PROCEDURE TO AMA;
GRANT EXECUTE ON UTL_FILE TO AMA;
GRANT CREATE ANY DIRECTORY TO AMA;
GRANT CREATE TYPE TO AMA;
GRANT SELECT_CATALOG_ROLE TO AMA;
GRANT EXECUTE_CATALOG_ROLE TO AMA;
GRANT EXECUTE ON DBMS_SQL TO AMA;
GRANT EXECUTE ON SYS.DBMS_SQL TO AMA;
GRANT EXECUTE ON DBMS_CRYPTO TO AMA;
GRANT EXECUTE ON UTL_I18N TO AMA;
CONNECT AMA/AMA@localhost:1521/FREEPDB1;